using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GunController : MonoBehaviour
{
    public static bool isActivate = true;
    // 현재 장착된 총
    [SerializeField] private Gun currentGun;
    //연사속도
    private float currentFireRate;
    //상태변수
    private bool isReload = false;
    [HideInInspector]
    public bool isFineSightMode = false;
    //본래 포지션값
    [SerializeField] private Vector3 originPos;
    //효과음재생
    private AudioSource audioSource;
    private RaycastHit hitInfo;
// 필요 컴포넌트
    [SerializeField]
    private Camera theCam;
    private Crosshair theCrosshair;
    //hit effect
    [SerializeField]
    private GameObject hit_effect_prefab;
    void Start()
    {
        originPos = Vector3.zero;
        audioSource = GetComponent<AudioSource>();
        theCrosshair = FindObjectOfType<Crosshair>();

        WeaponManager.currentWeapon = currentGun.GetComponent<Transform>();
        WeaponManager.currentWeaponAnim = currentGun.anim;
    }

    void Update()
    {
        if (isActivate)
        {
            GunFireRateCalc();
            TryFire();
            TryReload();
            TryFineSight();
        }

    }
    //연사속도 재계산
    private void GunFireRateCalc()
    {
        if (currentFireRate > 0)
            currentFireRate -= Time.deltaTime;
    }

    private void TryFire()
    {
        if (Input.GetButton("Fire1") && currentFireRate <= 0 && !isReload)
        {
            Fire();
        }

    }
    private void Fire()
    {
        if (!isReload)
        {
            if (currentGun.currentBulletCount > 0)
            {

                Shoot();
            }
            else
            {
                CancelFineSight();
                StartCoroutine(ReloadCoroutine());
            }
        }


    }
    private void TryReload()
    {
        if (Input .GetKeyDown (KeyCode.R)&&!isReload && currentGun.currentBulletCount<currentGun.reloadBulletCount)
        {
            CancelFineSight();
            StartCoroutine(ReloadCoroutine());
        }
    }
    public void CancelReload()
    {
        if (isReload)
        {
            StopAllCoroutines();
            isReload = false;
        }
    }
    IEnumerator ReloadCoroutine()
    {
        if (currentGun.anim == null)
        {
            Debug.LogError("애니메이터 없음");
        }
        else
        {
        
            currentGun.anim.SetTrigger("Reload");
        }

        if (currentGun.carryBulletCount > 0)
        {
            isReload = true;
            currentGun.anim.SetTrigger("Reload");

            yield return new WaitForSeconds(currentGun.reloadTime);

            int bulletToReload = currentGun.reloadBulletCount - currentGun.currentBulletCount;

            // 실제 장전 가능한 탄 수 계산
            if (currentGun.carryBulletCount >= bulletToReload)
            {
                currentGun.carryBulletCount -= bulletToReload;
                currentGun.currentBulletCount += bulletToReload;
            }
            else
            {
                currentGun.currentBulletCount += currentGun.carryBulletCount;
                currentGun.carryBulletCount = 0;
            }

            isReload = false;
        }
        else
        {
            Debug.Log("총알없음");
        }
    }

    private void TryFineSight()
    {
        if (Input.GetButtonDown("Fire2")&& !isReload )
        {
            FineSight();
        }
    }
    public void CancelFineSight()
    {
        if (isFineSightMode)
        {
            FineSight();
        }
    }
    private void FineSight()
    {
        isFineSightMode = !isFineSightMode;
        currentGun.anim.SetBool("FineSightMode", isFineSightMode);
        theCrosshair.FineSightAnimation(isFineSightMode);
        if (isFineSightMode)
        {
            StopAllCoroutines();
            StartCoroutine(FineSightActivatecoroutine());
        }
        else
        {
            StopAllCoroutines();
            StartCoroutine(FineSightDeactivatecoroutine());
        }

    }
    IEnumerator FineSightActivatecoroutine()
    {
        while(currentGun .transform .localPosition!= currentGun.fineSightOriginPos)
        {
            currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition, currentGun.fineSightOriginPos, 0.2f);
            yield return null;
        }
    }
    IEnumerator FineSightDeactivatecoroutine()
    {
        while (currentGun.transform.localPosition != originPos)
        {
            currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition,originPos, 0.2f);
            yield return null;
        }
    }
    private void Shoot()
    {
        theCrosshair.FireAnimation();
        currentGun.currentBulletCount--;
        currentFireRate = currentGun.fireRate;
        PlaySE(currentGun.fire_Sound);
        currentGun .muzzleFlash.Play();
        Hit();
        StopAllCoroutines();
        StartCoroutine (RetroActionCoroutine());
    }
    private void Hit()
    {
        if (Physics.Raycast(theCam.transform.position,theCam.transform.forward+
            new Vector3(Random .Range (-theCrosshair .GetAccuracy()-currentGun .accuracy, theCrosshair.GetAccuracy() + currentGun.accuracy),
                        Random.Range(-theCrosshair.GetAccuracy() - currentGun.accuracy, theCrosshair.GetAccuracy() + currentGun.accuracy),
                        0)
            ,out hitInfo, currentGun.range))
        {
            GameObject clone = Instantiate(hit_effect_prefab, hitInfo.point, Quaternion.LookRotation(hitInfo.normal));
            Destroy(clone, 2f);
        }
    }
    IEnumerator RetroActionCoroutine()
    {
        Vector3 recoilBack = new Vector3(currentGun.retroActionForce, originPos.y, originPos.z);
        Vector3 retroActionRecoilBack = new Vector3(currentGun.retroActionFineSightForce, currentGun.fineSightOriginPos.y, currentGun.fineSightOriginPos.z);
     
        if (!isFineSightMode)
        {
            currentGun.transform.localPosition = originPos;
            //반동시작
            while (currentGun .transform .localPosition .x <= currentGun.retroActionForce-0.02f)
            {
                currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition, recoilBack, 0.4f);
                yield return null ;
            }
            //원위치
            while (currentGun.transform.localPosition!=originPos)
            {
                currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition,originPos , 0.1f);
                yield return null;
            }
        }
        else
        {
            currentGun.transform.localPosition = currentGun.fineSightOriginPos;
            //반동시작
            while (currentGun.transform.localPosition.x <= currentGun.retroActionFineSightForce - 0.02f)
            {
                currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition, retroActionRecoilBack, 0.4f);
                yield return null;
            }
            //원위치
            while (currentGun.transform.localPosition!= currentGun.fineSightOriginPos)
            {
                currentGun.transform.localPosition = Vector3.Lerp(currentGun.transform.localPosition, currentGun.fineSightOriginPos, 0.1f);
                yield return null;
            }
        }
    }
    private void PlaySE(AudioClip _clip)
    {
        audioSource.clip = _clip;
        audioSource.Play();
    }
    public Gun GetGun()
    {
        return currentGun;
    }
    public bool GetFineSightMode()
    {
        return isFineSightMode;
    }
    public void GunChange(Gun _gun)
    {
        if (WeaponManager.currentWeapon != null)
            WeaponManager.currentWeapon.gameObject.SetActive(false);

        currentGun = _gun;
        WeaponManager.currentWeapon = currentGun.GetComponent<Transform>();
        WeaponManager.currentWeaponAnim = currentGun.anim;
        currentGun.transform.localPosition = Vector3.zero;
        currentGun.gameObject.SetActive(true);
        isActivate = true;
    }
}